spring:
  datasource:
    url: jdbc:postgresql://db:5432/pneumonia
    username: ${DB_USER:postgres}
    password: ${DB_PASS:example}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # create tables automatically if missing
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always   # run schema.sql & data.sql on startup
