spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Pneumonia;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===== SERVER =====
server.port=8080

# Tên ứng dụng
spring.application.name=PneumoniaDiagnosis

spring.web.cors.allowed-origins=http://localhost:5173

# JWT Configuration
jwt.secret=yourSuperSecretKeyForPneumoniaSystem2026
jwt.expiration=86400000   # 24 giờ (miliseconds)

# Tắt log security để sạch console (tùy chọn)
logging.level.org.springframework.security=ERROR

# ===== STATIC RESOURCES - Serve uploaded images =====
spring.web.resources.static-locations=file:D:\\TieuLuan\\pneumonia-diagnosis-system\\backend\\uploads\\,classpath:/static/