ALTER TABLE users ALTER COLUMN username NVARCHAR(100) NOT NULL;
ALTER TABLE users ALTER COLUMN email NVARCHAR(150) NOT NULL;
ALTER TABLE users ALTER COLUMN password NVARCHAR(255) NOT NULL;
ALTER TABLE users ALTER COLUMN status NVARCHAR(20) NULL;
ALTER TABLE users ALTER COLUMN phone NVARCHAR(20) NULL;
ALTER TABLE users ALTER COLUMN address NVARCHAR(255) NULL;
ALTER TABLE users ALTER COLUMN locked_reason NVARCHAR(255) NULL;
ALTER TABLE users ALTER COLUMN full_name NVARCHAR(255) NULL;
ALTER TABLE users ALTER COLUMN gender NVARCHAR(20) NULL;